# Generated by Django 6.0.3 on 2026-03-19 12:12

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('sexe', models.CharField(blank=True, choices=[('M', 'Masculin'), ('F', 'Feminin')], max_length=1, null=True, verbose_name='Sexe')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Utilisateur Systeme',
                'verbose_name_plural': 'Utilisateurs Systeme',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Ecole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200, unique=True)),
                ('abreviation', models.CharField(max_length=20, unique=True)),
                ('adresse', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialite', models.CharField(max_length=100)),
                ('ecole', models.ManyToManyField(related_name='enseignant', to='appels.ecole')),
            ],
            options={
                'verbose_name': 'Enseignant',
                'verbose_name_plural': 'Enseignants',
            },
            bases=('appels.personne',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('personne_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('matricule', models.CharField(max_length=100, unique=True)),
                ('ecole', models.ManyToManyField(related_name='etudiant', to='appels.ecole')),
            ],
            options={
                'verbose_name': 'Etudiant',
                'verbose_name_plural': 'Etudiants',
            },
            bases=('appels.personne',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('code', models.CharField(max_length=15)),
                ('credit', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=100)),
                ('ecole', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matieres', to='appels.ecole')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matieres', to='appels.enseignant')),
            ],
        ),
        migrations.CreateModel(
            name='FeuilleAppel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('description', models.CharField(blank=True, help_text='Ex, cours sur le beton armée', max_length=255)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feuilles_appel', to='appels.matiere')),
            ],
        ),
        migrations.CreateModel(
            name='Inscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nb_presences', models.PositiveBigIntegerField(default=0)),
                ('nb_abscences', models.PositiveBigIntegerField(default=0)),
                ('matiere', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels.matiere')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels.etudiant')),
            ],
            options={
                'unique_together': {('etudiant', 'matiere')},
            },
        ),
        migrations.AddField(
            model_name='etudiant',
            name='matieres',
            field=models.ManyToManyField(related_name='etudiants', through='appels.Inscription', to='appels.matiere'),
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_present', models.BooleanField(default=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('feuille', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='appels.feuilleappel')),
                ('etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appels.etudiant')),
            ],
            options={
                'unique_together': {('feuille', 'etudiant')},
            },
        ),
    ]
