# Generated by Django 6.0.3 on 2026-03-21 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feuilleappel',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
