# Generated by Django 6.0.3 on 2026-03-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0002_alter_feuilleappel_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuilleappel',
            name='code_validation',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='feuilleappel',
            name='is_actif',
            field=models.BooleanField(default=False),
        ),
    ]
