# Generated by Django 6.0.3 on 2026-03-21 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0003_feuilleappel_code_validation_feuilleappel_is_actif'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuilleappel',
            name='date_fin_appel',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
