# Generated by Django 6.0.3 on 2026-03-22 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0004_feuilleappel_date_fin_appel'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='latitude_prof',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='longitude_prof',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feuilleappel',
            name='rayon_autorise',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
