# Generated by Django 6.0.3 on 2026-03-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0005_enseignant_latitude_prof_enseignant_longitude_prof_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='latitude_prof',
        ),
        migrations.RemoveField(
            model_name='enseignant',
            name='longitude_prof',
        ),
        migrations.AddField(
            model_name='feuilleappel',
            name='latitude_prof',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feuilleappel',
            name='longitude_prof',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
