# Generated by Django 6.0.3 on 2026-03-22 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0006_remove_enseignant_latitude_prof_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscriptions', to='appels.matiere'),
        ),
    ]
