# Generated by Django 6.0.3 on 2026-03-22 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0007_alter_inscription_matiere'),
    ]

    operations = [
        migrations.AddField(
            model_name='matiere',
            name='est_pondere',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='matiere',
            name='points_absence',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='matiere',
            name='points_presence',
            field=models.FloatField(default=0.0),
        ),
    ]
