# Generated by Django 6.0.3 on 2026-03-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0008_matiere_est_pondere_matiere_points_absence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscription',
            name='note_actuelle',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
