# Generated by Django 6.0.3 on 2026-03-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0009_inscription_note_actuelle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='ecole',
        ),
        migrations.AddField(
            model_name='etudiant',
            name='ecole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etudiants', to='appels.ecole'),
        ),
    ]
