# Generated by Django 6.0.3 on 2026-03-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0010_remove_etudiant_ecole_etudiant_ecole'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='device_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
