# Generated by Django 6.0.3 on 2026-03-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0011_presence_device_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='feuilleappel',
            name='appel_lance',
            field=models.BooleanField(default=False),
        ),
    ]
