# Generated by Django 6.0.3 on 2026-07-26 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0012_feuilleappel_appel_lance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matiere',
            name='description',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
