# Generated by Django 6.0.3 on 2026-08-13 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appels', '0013_alter_matiere_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='ecole',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='etudiants', to='appels.ecole'),
        ),
    ]
